'use strict';
const $ = (id) => document.getElementById(id);
const icon = (name, cls='') => `<svg class="${cls}" aria-hidden="true"><use href="#ico-${name}"/></svg>`;
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let jobs=[], chosenPlatform='All', page=1, briefing={}, chosenLeague='NHL', loading=false;
const pageSize=12;
const dateFormat=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
function formatted(value){if(!value)return 'Not available';const d=new Date(value);return Number.isNaN(+d)?value:dateFormat.format(d);}
function relative(value){if(!value)return '';const d=new Date(value);if(Number.isNaN(+d))return '';const mins=Math.max(0,Math.round((Date.now()-d)/60000));return mins<1?'Just updated':mins<60?`${mins}m ago`:mins<1440?`${Math.floor(mins/60)}h ago`:`${Math.floor(mins/1440)}d ago`;}
function isFailed(j){return !['ok','success','unknown','never','none',''].includes(String(j.result).toLowerCase());}
function updateClock(){const d=new Date();$('clock').textContent=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',hour:'numeric',minute:'2-digit'}).format(d);$('today').textContent=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',weekday:'short',month:'short',day:'numeric'}).format(d);}
updateClock();setInterval(updateClock,1000);

async function getJSON(url){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw new Error('HTTP '+response.status);return await response.json();}finally{clearTimeout(timer);}}
async function loadJobs(){if(loading)return;loading=true;$('refresh').classList.add('busy');try{const data=await getJSON('/api/jobs');jobs=data.jobs;
 $('total').textContent=jobs.length;$('active').textContent=jobs.filter(j=>j.status==='active').length;$('inactive').textContent=jobs.filter(j=>j.status==='inactive').length;
 $('inactive-detail').textContent=`Including ${jobs.filter(j=>j.archived).length} migrated definitions`;
 $('all-count').textContent=jobs.length;$('job-count').textContent=jobs.length;
 ['Hermes','OpenClaw'].forEach(p=>$(p.toLowerCase()+'-count').textContent=jobs.filter(j=>j.platform===p||j.platform==='Both').length);
 const upcoming=jobs.filter(j=>j.status==='active'&&j.nextRun&&!/heartbeat|patch|cleanup|maintenance|watchdog|skill-collection/i.test(j.name+' '+j.id)&&!Number.isNaN(+new Date(j.nextRun))&&new Date(j.nextRun)>new Date()).sort((a,b)=>new Date(a.nextRun)-new Date(b.nextRun))[0];
 $('next-name').textContent=upcoming?.name||'No upcoming time available';$('next-time').textContent=upcoming?`${formatted(upcoming.nextRun)} · ${upcoming.platform}`:'Direct cron times are not predicted';
 $('connection').classList.toggle('error',data.errors.length>0);
 $('connection').innerHTML=Object.entries(data.gateways).map(([name,state])=>`<span class="gateway"><span class="dot ${state==='active'?'green':'red'}"></span>${esc(name)} gateway ${state==='active'?'online':esc(state)}</span>`).join('')+`<span>· &nbsp; Times in Toronto</span>`;
 $('footer-dot').className='dot '+(data.errors.length?'red':'green');
 $('last-sync').textContent=`Jobs synced ${formatted(data.updatedAt)} · Auto-refresh 30s`;
 $('inventory-warning').hidden=data.errors.length===0;$('inventory-warning').textContent=data.errors.join(' · ')+'. The inventory may be incomplete.';
 $('sources').innerHTML=data.sources.map(s=>`<div class="source-row"><strong><span class="dot ${s.ok?'green':'red'}"></span> ${esc(s.name)}</strong><span>${s.count} jobs · ${esc(s.note)}</span></div>`).join('');renderJobs();try{const log=await getJSON('/api/acknowledgements');for(const item of log.history||[])if(item.verification)noticeVerifications.set(item.identity,item.verification);}catch{}openLinkedJob();
 }catch(error){$('connection').classList.add('error');$('connection').textContent='Dashboard connection lost. Showing the last inventory; retrying in 30 seconds.';$('footer-dot').className='dot red';if(!jobs.length)$('job-rows').innerHTML='<tr><td colspan="5" class="empty">Could not load jobs. Use refresh to retry.</td></tr>';}finally{loading=false;$('refresh').classList.remove('busy');}}

function renderJobs(){const query=$('search').value.trim().toLowerCase();const status=$('status').value;
 const filtered=jobs.filter(j=>(chosenPlatform==='All'||j.platform===chosenPlatform||j.platform==='Both')&&(status==='all'||status==='archive'&&j.archived||status==='failed'&&isFailed(j)||status===j.status)&&(!query||[j.name,j.platform,j.source,j.schedule,j.unit,j.note].some(v=>String(v).toLowerCase().includes(query))));
 const pages=Math.max(1,Math.ceil(filtered.length/pageSize));page=Math.min(page,pages);const offset=(page-1)*pageSize;
 $('job-rows').innerHTML=filtered.slice(offset,offset+pageSize).map(j=>`<tr><td><button class="job-name" data-job="${esc(j.id)}" title="${esc(j.name)}">${esc(j.name)}</button><div class="job-source"><span>${esc(j.source)}</span>${j.archived?'<span class="archive-label">↗ migrated</span>':''}</div></td><td><span class="agent ${j.platform.toLowerCase()}"><span class="dot ${j.platform==='OpenClaw'?'blue':'purple'}"></span>${esc(j.platform)}</span></td><td><span class="status ${j.status}"><span class="dot ${j.status==='active'?'green':'gray'}"></span>${j.status==='active'?'Active':'Inactive'}</span></td><td><span class="schedule" title="${esc(j.schedule)}">${esc(j.schedule)}</span><div class="next-run" title="${esc(formatted(j.nextRun))}">${j.nextRun?'Next '+esc(formatted(j.nextRun)):j.archived?'Historical definition':j.status==='inactive'?'Not scheduled':'Next time unavailable'}</div></td><td><span class="result ${isFailed(j)?'failed':j.result==='unknown'?'unknown':''}">${j.result==='unknown'?'—':isFailed(j)?'! '+esc(j.result):'✓ Success'}</span><div class="last-run" title="${esc(formatted(j.lastRun))}">${j.lastRun?esc(relative(j.lastRun)):j.source==='System crontab'?'Not tracked':'No run history'}</div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No jobs match these filters.</td></tr>';
 $('range').textContent=filtered.length?`Showing ${offset+1}–${Math.min(offset+pageSize,filtered.length)} of ${filtered.length} jobs`:'0 matching jobs';$('page').textContent=`${page} / ${pages}`;$('previous').disabled=page===1;$('next').disabled=page===pages;
}
function showJobDetails(id){const j=jobs.find(x=>x.id===id);if(!j)return;$('detail-name').textContent=j.name;const values=[['Agent',j.platform==='Both'?'Shared Hermes / OpenClaw job':j.platform],['Scheduler',j.source],['Status',j.status==='active'?'Active':'Inactive'],['Schedule',j.schedule],['Timezone',j.timezone],['Next scheduled run',formatted(j.nextRun)],['Last trigger',formatted(j.lastRun)],['Last result',j.result],...(isFailed(j)?[['Reported cause',j.failureReason||'The scheduler did not provide a detailed cause.'],['Impact',jobFailureImpact(j)],['Action needed',jobFailureAction(j)],['Next attempt',j.status!=='active'?'This schedule is inactive.':j.nextRun?'Next scheduled attempt '+formatted(j.nextRun)+'. This is scheduled, not a confirmed recovery.':'No next attempt is available. The schedule needs a check.']]:[]),['Definition / unit',j.unit],['Notes',j.note||'No additional notes']];$('detail-values').innerHTML=values.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');$('job-dialog').showModal();}
let linkedJobOpened=null;
function openLinkedJob(){if(!location.hash.startsWith('#job=')){linkedJobOpened=null;return;}const id=decodeURIComponent(location.hash.slice(5));if(jobs.some(j=>j.id===id)&&linkedJobOpened!==id){linkedJobOpened=id;showJobDetails(id);}}
window.addEventListener('hashchange',()=>{if($('job-rows'))openLinkedJob();});
if($('job-rows')) {
document.querySelectorAll('[data-platform]').forEach(b=>b.addEventListener('click',()=>{chosenPlatform=b.dataset.platform;page=1;document.querySelectorAll('[data-platform]').forEach(x=>x.classList.toggle('selected',x===b));renderJobs();}));
$('search').addEventListener('input',()=>{page=1;renderJobs();});$('status').addEventListener('change',()=>{page=1;renderJobs();});$('previous').addEventListener('click',()=>{page--;renderJobs();});$('next').addEventListener('click',()=>{page++;renderJobs();});$('refresh').addEventListener('click',loadJobs);
$('job-rows').addEventListener('click',(event)=>{const b=event.target.closest('[data-job]');if(b)showJobDetails(b.dataset.job);});
$('close-dialog').addEventListener('click',()=>$('job-dialog').close());$('job-dialog').addEventListener('click',event=>{if(event.target===$('job-dialog')){const r=$('job-dialog').getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)$('job-dialog').close();}});
}

function condition(code){if(code===0)return 'Clear skies';if(code<=3)return ['','Mainly clear','Partly cloudy','Overcast'][code];if(code<=48)return 'Foggy';if(code<=57)return 'Drizzle';if(code<=67)return 'Rain';if(code<=77)return 'Snow';if(code<=82)return 'Rain showers';if(code<=86)return 'Snow showers';return 'Thunderstorms';}
function freshnessBadge(state,label){const labels={current:'Current',older:'Older report',cached:'Cached',overdue:'Overdue',unavailable:'Unavailable'};return `<span class="freshness-badge freshness-${state}">${esc(label||labels[state]||state)}</span>`;}
function markCached(root=document){root.querySelectorAll('.freshness-badge').forEach(el=>{el.className='freshness-badge freshness-cached';el.textContent='Cached';});}
function reportFreshness(value){if(!value)return 'unavailable';return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))===new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())?'current':'older';}
function widgetTime(id,feed){const el=$(id);const state=feed?.data?(feed.stale||feed.error||!feed.updatedAt||Date.now()-Date.parse(feed.updatedAt)>1200000?'cached':'current'):'unavailable';el.innerHTML=freshnessBadge(state)+' '+esc(feed?.updatedAt?'Updated '+formatted(feed.updatedAt):feed?.error?'Retrying automatically':'Updating…');el.classList.toggle('stale',state==='cached');el.title=feed?.error||formatted(feed?.updatedAt);}
function renderWeather(){const f=briefing.weather;widgetTime('weather-time',f);if(!f?.data){$('weather').className='loading';$('weather').textContent=f?.error?'Weather is temporarily unavailable. Retrying automatically.':'Fetching the forecast…';return;}const w=f.data;const c=w.current;const daily=w.daily;$('weather-city').textContent=w.city;$('weather').className='';$('weather').innerHTML=`<div class="weather-now"><div><div class="temperature">${Math.round(c.temperature_2m)}<span>°C</span></div><div class="condition">${esc(condition(c.weather_code))}</div></div>${icon(c.weather_code<=2?'sun':'cloud','weather-art')}</div><div class="weather-meta"><span>Feels like ${Math.round(c.apparent_temperature)}°</span><span>Wind ${Math.round(c.wind_speed_10m)} km/h</span></div><div class="forecast">${daily.time.map((day,i)=>`<div class="forecast-day">${i===0?'Today':new Intl.DateTimeFormat('en',{weekday:'short',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'))}<strong>${Math.round(daily.temperature_2m_max[i])}°</strong><span>${Math.round(daily.temperature_2m_min[i])}°</span></div>`).join('')}</div>`;}
function safeURL(url){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?esc(u.href):'#';}catch{return '#';}}
function headlineMarkup(items,limit,withSummary=false){return items.slice(0,limit).map((item,i)=>`<a class="headline" href="${safeURL(item.url)}" target="_blank" rel="noopener noreferrer"><span class="headline-number">${String(i+1).padStart(2,'0')}</span><div><span class="headline-title">${esc(item.title)}</span>${withSummary&&item.summary?`<p class="headline-summary">${esc(item.summary)}</p>`:''}<div class="headline-meta">${esc(item.source)} · ${esc(relative(item.published))}</div></div></a>`).join('');}
function renderHeadlines(kind,limit){const f=briefing[kind];const isNews=kind==='news'||kind==='usnews';if(isNews){widgetTime(kind+'-time',f);$(kind+'-source').textContent=f?.data?.source||'News feeds';}const el=$(kind);if(f?.data){el.className=isNews?'headline-list':'sports-headlines';el.innerHTML=headlineMarkup(f.data.items,limit,isNews);}else{el.className=isNews?'headline-list loading':'sports-headlines';el.textContent=f?.error?'Headlines temporarily unavailable. Retrying automatically.':isNews?'Fetching the latest headlines…':'';}}
function renderScores(){const f=briefing.scores;widgetTime('sports-time',f);const el=$('scores');if(!f?.data){el.className='score-list loading';el.textContent=f?.error?'Scores temporarily unavailable. Retrying automatically.':'Fetching today’s games…';return;}el.className='score-list';document.querySelectorAll('[data-league]').forEach(b=>{const l=f.data.leagues.find(l=>l.league===b.dataset.league);b.innerHTML=scoreLeagueMarkup(b.dataset.league,l?.logo,l?.events.length);b.setAttribute('aria-label',b.dataset.league);b.setAttribute('aria-pressed',String(b.dataset.league===chosenLeague));});const league=f.data.leagues.find(l=>l.league===chosenLeague);if(!league){el.innerHTML='<div class="no-games">This league’s scoreboard is temporarily unavailable.</div>';return;}$('scoreboard-day').textContent=(f.data.date?new Intl.DateTimeFormat('en-CA',{weekday:'long',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(f.data.date+'T12:00:00Z')):'Cached scoreboard')+' · '+chosenLeague+' · '+league.events.length+' game'+(league.events.length===1?'':'s')+' · Toronto time';el.innerHTML=league.events.map(g=>`<a class="game" href="${safeURL(g.url)}" target="_blank" rel="noopener noreferrer"><div class="game-title ${g.state==='in'?'live':''}"><span>${g.state==='in'?'● LIVE':g.state==='post'?'FINAL':esc(formatted(g.date))}</span><span>${esc(g.status)}</span></div><div class="game-teams">${scoreTeamMarkup(g.teams[0],'away')}<span class="game-score ${g.state==='pre'?'pregame':''}">${g.state==='pre'?'VS':esc(g.teams[0]?.score)+' – '+esc(g.teams[1]?.score)}</span>${scoreTeamMarkup(g.teams[1],'home')}</div></a>`).join('')||'<div class="no-games">No games on today’s schedule.</div>';applyScoreTeamColors(el);}
document.querySelectorAll('[data-league]').forEach(b=>b.addEventListener('click',()=>{chosenLeague=b.dataset.league;document.querySelectorAll('[data-league]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});renderScores();}));
async function loadBriefing(){try{briefing=await getJSON('/api/briefing');renderWeather();renderHeadlines('news',4);renderHeadlines('usnews',4);renderHeadlines('sports',2);renderScores();}catch{for(const id of ['weather-time','news-time','usnews-time','sports-time']){$(id).textContent='Connection lost';$(id).classList.add('stale');}}}
if($('job-rows')) { loadJobs(); setInterval(loadJobs,30000); }
if($('weather')) { loadBriefing(); setInterval(loadBriefing,30000); }
