'use strict';
let racingData=null, racingDate=new URLSearchParams(location.search).get('date')||'', racingRequest=0;
const re=(id)=>document.getElementById(id);
const raceDateLabel=(date)=>new Intl.DateTimeFormat('en-CA',{weekday:'short',month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
const scoreText=(value)=>typeof value==='number'?value.toFixed(1):esc(value??'—');
// Palette: Hermes saddlecloth.md; positions 1–12 also match OpenClaw smartpick_escraper.py.
const saddleclothNames={1:"Red cloth, white number",2:"White cloth, black number",3:"Blue cloth, white number",4:"Yellow cloth, black number",5:"Green cloth, white number",6:"Black cloth, yellow number",7:"Orange cloth, black number",8:"Pink cloth, black number",9:"Dark Cyan cloth, black number",10:"Purple cloth, white number",11:"Gray cloth, red number",12:"Lime Green cloth, black number",13:"Brown cloth, white number",14:"Brown cloth, yellow number",15:"Khaki cloth, black number",16:"Light Blue cloth, orange number",17:"Navy cloth, white number",18:"Dark Green cloth, yellow number",19:"Steel Blue cloth, red number",20:"Deep Pink cloth, yellow number",21:"Lavender cloth, navy number",22:"Dark Blue cloth, white number"};
function saddleclothBadge(pp){
 const label=String(pp??'').trim().toUpperCase();
 const match=/^(\d{1,2})([A-Z]?)$/.exec(label);
 const number=match?Number(match[1]):0;
 const known=Object.hasOwn(saddleclothNames,number);
 const description=known?`Program ${label} · ${saddleclothNames[number]}`:label?`Program ${label} · color unavailable`:'Program number unavailable';
 return `<span class="saddlecloth saddlecloth-${known?number:'unknown'}" title="${esc(description)}" aria-label="${esc(description)}">${esc(label||'?')}</span>`;
}
function racingPick(h,metric){return `<div class="pick-row ${h.scratched?'scratched':''}"><span class="pick-rank" title="Pick rank" aria-label="Pick rank ${esc(h.rank)}">${String(h.rank).padStart(2,'0')}</span><div><div class="pick-name">${saddleclothBadge(h.pp)}${esc(h.name)}</div>${h.scratched?'<div class="scratch-tag">SCRATCHED · original rank retained</div>':''}${h.finish?`<div class="finish-tag ${h.finish===1?'finish-win':''}">Finished ${h.finish===1?'1st':h.finish===2?'2nd':h.finish===3?'3rd':h.finish+'th'}</div>`:''}<div class="pick-figures">${esc(metric)} figures: ${h.figures.length?h.figures.map(esc).join(' · '):'No figures recorded'}</div>${h.note?`<div class="pick-note">${esc(h.note)}</div>`:''}${!h.ppVerified?'<div class="pick-note">Program number unverified</div>':''}</div><div class="pick-score">${scoreText(h.avg)}<small>${esc(metric)} avg</small></div></div>`;}
function renderRacing(){const data=racingData;if(!data)return;
 renderAgco(data.agco,data.date);renderResults(data);
 const openDetails=new Set([...document.querySelectorAll('[data-racing-detail][open]')].map(d=>d.dataset.racingDetail));
 const chosen=re('race-filter').value;
 const shown=data.races.filter(r=>chosen==='all'||String(r.number)===chosen);
 re('racing-races').textContent=data.races.length;
 re('racing-scratch-count').textContent=data.scratches.available?data.scratches.items.length:'—';
 re('racing-source-count').textContent=data.sources.filter(s=>s.available).length+'/2';
 re('racing-card-date').textContent=`${raceDateLabel(data.date)}${data.date===data.today?' · Today’s card':' · Archived card'}`;
 re('racing-status').textContent=data.errors.length?data.errors.join(' · '):data.refreshing?'Saved picks loaded. Checking TrackData scratches and changes…':`Saved picks loaded · Scratch feed checked ${formatted(data.scratches.checkedAt)}`;
 re('racing-sources').innerHTML=data.sources.map(s=>`<article class="panel racing-source ${s.agent.toLowerCase()}"><div class="source-agent"><span class="dot ${s.agent==='Hermes'?'purple':'blue'}"></span>${esc(s.agent)}</div><h2>${esc(s.label)}</h2>${freshnessBadge(s.available?(data.date===data.today?'current':'older'):'unavailable')}<p>${s.available?'Saved '+esc(formatted(s.savedAt)):'No saved output for this race date'}</p><details><summary>How these selections were made</summary><p>${esc(s.method)}</p>${s.file?`<p>Saved source: <code>${esc(s.file)}</code></p>`:''}</details>${s.document?`<a class="source-report" href="${safeURL(new URL(s.document,location.origin).href)}" target="_blank" rel="noopener noreferrer">Open original PDF ↗</a>`:''}</article>`).join('');
 const sf=data.scratches;
 re('scratch-note').className='scratch-feed-note'+(sf.error||sf.snapshot?' stale':'');
 re('scratch-note').textContent=sf.available?`${sf.source} · ${sf.snapshot?'Recorded when picks were saved':'Checked'} ${formatted(sf.checkedAt)}${sf.snapshot?' · Latest daily feed has not been confirmed.':''}${sf.error?' · '+sf.error:''}`:'Scratch information is unavailable. Retrying automatically.';
 re('scratch-list').innerHTML=sf.items.length?sf.items.map(s=>`<div class="scratch-item"><span class="scratch-race">Race ${esc(s.race)} · ${saddleclothBadge(s.pp)}</span><strong>${esc(s.name)}</strong><p>${esc(s.reason)}</p></div>`).join(''):`<div class="racing-empty">${!sf.available?'No scratch data available.':sf.snapshot?'No scratches recorded in the saved picks snapshot.':"No scratches reported by TrackData for this card."}</div>`;
 re('change-count').textContent=data.changes.items.length;
 re('change-list').innerHTML=data.changes.items.map(c=>`<div class="change-item"><strong>Race ${esc(c.race)}</strong><span>${c.pp?saddleclothBadge(c.pp)+' ':''}${esc(c.name)} — ${esc(c.reason)}</span></div>`).join('')||'<p>No other changes recorded.</p>';
 re('change-source').textContent=`${data.changes.source}${data.changes.error?' · '+data.changes.error:''}`;
 re('race-cards').innerHTML=shown.map(r=>`<article class="panel race-card"><header class="race-heading"><div><h2>Race ${r.number}</h2><div class="race-meta">${[r.conditions,r.distance,r.surface].filter(Boolean).map(esc).join(' · ')}</div></div>${r.postTime?`<time>Post ${esc(r.postTime)} · Toronto</time>`:''}</header>${resultLine(r.result)}<div class="race-comparison"><section class="race-agent"><div class="race-agent-heading"><strong>Hermes · DRF Beyer</strong><span>Saved top-three picks</span></div>${r.hermes.map(h=>racingPick(h,'Beyer')).join('')||'<p class="racing-empty">No Hermes picks saved for this race.</p>'}<details class="race-details"><summary>Figures and selection rules</summary><p>Ranked by the available positive figures in the last three DRF Beyer slots. A missing figure does not count in the average. Ties use the lower program number. These are the saved picks; a newly scratched horse is marked without rewriting the original order.</p>${r.audit.source?`<p>Recorded figure source: ${esc(r.audit.source.replaceAll('_',' '))}.</p>`:''}${r.audit.runnersWithFigures!=null?`<p>${r.audit.runnersWithFigures} of ${r.audit.runners} runners had parsed Beyer figures at generation.</p>`:''}${r.audit.untrusted?'<p class="stale">The saved audit marks this extraction as untrusted.</p>':''}</details>${r.reviews.length?`<details class="race-review"><summary>${r.reviews.length} recorded data / review notes</summary><ul>${r.reviews.map(n=>`<li>${esc(n.title)}${n.horses.length?' · '+n.horses.map(esc).join(', '):''}</li>`).join('')}</ul></details>`:''}</section><section class="race-agent openclaw"><div class="race-agent-heading"><strong>OpenClaw · Equibase E-speed</strong><span>Highest saved averages</span></div>${r.openclaw.slice(0,3).map(h=>racingPick(h,'E-speed')).join('')||'<p class="racing-empty">No OpenClaw rankings saved for this race.</p>'}${r.openclaw.length?`<details class="race-details"><summary>All ${r.openclaw.length} E-speed rankings & figures</summary><p>Sorted by saved average of the latest three E-speed figures, excluding 999 placeholders. Missing figures stay missing. Program numbers are matched to named entries; they are not guessed from row order. Scratches are marked without changing the saved ranking.</p>${r.openclaw.map(h=>racingPick(h,'E-speed')).join('')}</details>`:''}</section></div><div class="official-pick"><span>★ Equibase’s own SmartPick</span><strong>${r.official?saddleclothBadge(r.official.pp)+' '+esc(r.official.name||'Horse name not verified')+(r.official.scratched?' · SCRATCHED':''):'Not recorded for this race'}</strong>${r.equibaseURL?`<a href="${safeURL(r.equibaseURL)}" target="_blank" rel="noopener noreferrer">View Equibase source ↗</a>`:''}</div></article>`).join('')||'<div class="panel racing-empty loading">No saved picks for this date. Choose an archived card to review previous outputs.</div>';
 document.querySelectorAll('#racing-sources details,#race-cards details').forEach((d,i)=>{d.dataset.racingDetail=data.date+'-'+chosen+'-'+i;d.open=openDetails.has(d.dataset.racingDetail);});
}
async function loadRacing(){const request=++racingRequest;re('racing-refresh').classList.add('busy');try{const data=await getJSON('/api/racing'+(racingDate?'?date='+encodeURIComponent(racingDate):''));if(request!==racingRequest)return;racingData=data;racingDate=data.date;const selectedRace=re('race-filter').value;re('racing-date').innerHTML=data.dates.map(d=>`<option value="${d}"${d===data.date?' selected':''}>${d===data.today?'Today · ':''}${esc(raceDateLabel(d))}</option>`).join('');re('race-filter').innerHTML='<option value="all">All races</option>'+data.races.map(r=>`<option value="${r.number}">Race ${r.number}</option>`).join('');if([...re('race-filter').options].some(o=>o.value===selectedRace))re('race-filter').value=selectedRace;renderRacing();}catch{if(request!==racingRequest)return;document.querySelectorAll('.racing-source,.results-panel,.agco-panel,#race-cards').forEach(markCached);re('racing-status').textContent='Could not refresh racing data. Showing the last loaded card; retrying automatically.';}finally{if(request===racingRequest)re('racing-refresh').classList.remove('busy');}}
re('racing-date').addEventListener('change',()=>{racingDate=re('racing-date').value;racingData=null;re('race-filter').value='all';re('racing-status').textContent='Loading selected card…';re('racing-card-date').textContent=raceDateLabel(racingDate);for(const id of ['racing-races','racing-scratch-count','racing-source-count','change-count'])re(id).textContent='—';for(const id of ['racing-sources','scratch-list','change-list','change-source'])re(id).innerHTML='';re('results-comparison').textContent='Loading results for the selected card…';re('agco-body').textContent='Checking the selected race date…';re('scratch-note').textContent='Checking the selected date…';re('race-cards').innerHTML='<div class="racing-empty">Loading selected card…</div>';loadRacing();});
function renderAgco(report,date){
 const el=re('agco-body');
 if(!report?.available){el.innerHTML=`${freshnessBadge('unavailable')}<p class="agco-date">${esc(raceDateLabel(date))}</p><p class="agco-note">No saved AGCO report for this date yet. Reports appear after racing once published and saved.</p>`;return;}
 const s=report.summary;
 el.innerHTML=`${freshnessBadge(date===racingData?.today?'current':'older')}<p class="agco-date">${esc(raceDateLabel(date))} · Senior Stewards Report · Woodbine</p>${s?`<div class="agco-summary">${[['Races',s.races],['Vet scratches',s.vetScratches],['Stewards scratches',s.stewardScratches],['Reported handle',s.handle]].map(([label,value])=>`<div><span>${label}</span><strong>${esc(value??'—')}</strong></div>`).join('')}</div>${s.weather?`<p class="agco-condition"><strong>Weather</strong> ${esc(s.weather)}</p>`:''}${s.track?`<p class="agco-condition"><strong>Track</strong> ${esc(s.track)}</p>`:''}`:''}<p class="agco-note">${report.error?esc(report.error):'Read the full report for race-by-race notes, inquiries, claims, and any recorded violations. Scratch counts reflect the stewards report for this card.'}</p><div class="agco-links">${report.formatted?`<a class="source-report" href="${safeURL(new URL(report.formatted,location.origin).href)}" target="_blank" rel="noopener noreferrer">Open report ↗</a>`:''}${report.original?`<a class="source-report" href="${safeURL(new URL(report.original,location.origin).href)}" target="_blank" rel="noopener noreferrer">Original AGCO PDF ↗</a>`:''}</div>`;
}
re('race-filter').addEventListener('change',renderRacing);
re('racing-refresh').addEventListener('click',loadRacing);
loadRacing();setInterval(loadRacing,30000);

function resultLine(result){return `<div class="result-line">${freshnessBadge(result.cached?'cached':result.complete?'current':'unavailable',result.complete?'Results available':'Results pending')}<span>${result.complete?'Completed result · TrackData / Equibase':'Completed finishing order not available yet'}${result.checkedAt?' · Checked '+esc(formatted(result.checkedAt)):''}</span>${result.chart?`<a href="${safeURL(result.chart)}" target="_blank" rel="noopener noreferrer">Result chart ↗</a>`:''}</div>`;}
function renderResults(data){const c=data.comparison;re('results-comparison').innerHTML=`<p class="results-period">${esc(raceDateLabel(c.date))} only · ${c.completed}/${data.races.length} races have complete results · ${c.eligible} shared races scored</p><div class="results-grid">${c.agents.map(a=>`<article><h3>${esc(a.agent)}</h3><div><span>Top-pick win rate</span><strong>${a.winPct==null?'—':a.winPct.toFixed(1)+'%'}</strong><small>${a.wins} / ${a.races} races</small></div><div><span>Winner in first 3 picks</span><strong>${a.hitPct==null?'—':a.hitPct.toFixed(1)+'%'}</strong><small>${a.hits} / ${a.races} races</small></div></article>`).join('')}</div><details class="results-rules"><summary>What counts toward these percentages</summary><p>Both agents use the same completed races on this selected date. Reports must have been saved before the race’s post time. Every saved top-three selection must match a result entry, and neither agent’s original first pick can be scratched. No substitute picks are promoted. A top-three hit means the winner appeared among the original first three picks, not that all three finished in order. Races with incomplete finishing data are excluded. These are source-reported results, not an independent stewards certification.</p></details>`;}

let performanceData=null;
const performanceMoney=n=>new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(n);
function renderPerformance(){
 const d=performanceData;if(!d)return;
 const period=re('performance-period').value, today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const cutoff=new Date(today+'T12:00:00Z');cutoff.setUTCDate(cutoff.getUTCDate()-Number(period||0)+1);
 const days=d.days.filter(x=>period==='all'||x.date>=cutoff.toISOString().slice(0,10));
 const agents=['Hermes','OpenClaw'].map((name,i)=>{const a={agent:name,races:0,wins:0,hits:0,wagerRaces:0,stake:0,returned:0,profit:0};for(const day of days)for(const k of ['races','wins','hits','wagerRaces','stake','returned','profit'])a[k]+=day.agents[i][k]||0;return a;});
 const scored=days.filter(x=>x.eligible);
 re('performance-body').innerHTML=`<p class="performance-progress">${scored.length} scored race days · ${d.checked}/${d.total} paired saved cards checked${d.refreshing?' · Checking history in the background…':''}${d.errors?' · '+d.errors+' cards had incomplete source checks':''}${d.checkedAt?' · Checked '+esc(formatted(d.checkedAt)):''}</p>${scored.length?`<div class="results-grid">${agents.map(a=>`<article><h3>${a.agent}</h3><div><span>First-pick wins</span><strong>${a.races?(100*a.wins/a.races).toFixed(1)+'%':'—'}</strong><small>${a.wins} wins / ${a.races} shared races</small></div><div><span>Winner among first 3 picks</span><strong>${a.races?(100*a.hits/a.races).toFixed(1)+'%':'—'}</strong><small>${a.hits} / ${a.races} shared races</small></div><div><span>Hypothetical $2 win return</span><strong>${a.wagerRaces?performanceMoney(a.returned):'—'}</strong><small>${a.wagerRaces} wager races · ${performanceMoney(a.stake)} staked</small></div><div><span>Net return / ROI</span><strong>${a.stake?performanceMoney(a.profit):'—'}</strong><small>${a.stake?(100*a.profit/a.stake).toFixed(1)+'% ROI':'Winning payout data unavailable'}</small></div></article>`).join('')}</div>`:'<p class="performance-empty">No shared races can be scored for this period yet. Reports saved after post time, scratched first picks, unmatched horses and incomplete results are excluded.</p>'}`;
 re('performance-body').querySelectorAll('article h3').forEach(h=>h.insertAdjacentHTML('afterend','<small class="performance-method">'+(h.textContent==='Hermes'?'DRF Beyer':'Equibase E-speed')+' rankings</small>'));
 re('performance-history').innerHTML=scored.map(x=>`<div class="performance-day"><a href="/woodbine?date=${esc(x.date)}">${esc(raceDateLabel(x.date))} ↗<small>${x.eligible} shared races scored</small></a>${x.agents.map(a=>`<span><strong>${esc(a.agent)} · ${a.wins}/${a.races} wins</strong><small>${a.wagerRaces?performanceMoney(a.profit)+' net · '+a.roi.toFixed(1)+'% ROI':'Payouts not scored'}</small></span>`).join('')}</div>`).join('')||'<p>No scored days in this period.</p>';
}
async function loadPerformance(){try{performanceData=await getJSON('/api/racing-performance');renderPerformance();}catch{markCached(re('performance-body'));re('performance-body').insertAdjacentHTML('afterbegin','<p class="performance-empty performance-error">History could not be refreshed. Retrying automatically.</p>');}}
re('performance-period').addEventListener('change',renderPerformance);loadPerformance();setInterval(loadPerformance,30000);
