'use strict';
let statsData=null;
const statsMoney=v=>v==null?'—':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(v);
const statsPct=v=>v==null?'—':(v>0?'+':'')+v.toFixed(1)+'%';
const statsTone=v=>v>0?'stats-up':v<0?'stats-down':'';
const statsDate=v=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(v+'T12:00:00Z'));
function renderHandle(h){
 const el=document.getElementById('handle-body');
 if(h.error){el.innerHTML=freshnessBadge('unavailable')+' '+esc(h.error);return;}
 const maximum=Math.max(...h.weekdays.flatMap(d=>[d.previous.average||0,d.current.average||0]));
 el.innerHTML=`${freshnessBadge(reportFreshness(h.through+'T23:59:00-04:00'))}<p class="stats-note">First ${h.current.days} completed race days in each season · 2026 through ${esc(statsDate(h.through))} vs. 2025 through ${esc(statsDate(h.priorThrough))}. CAD · From your existing matched race-day report.</p><div class="handle-metrics"><div><span>2025 · first ${h.previous.days} race days</span><strong>${statsMoney(h.previous.handle)}</strong><small>${h.previous.days} racing days · ${h.previous.races} races</small></div><div><span>2026 · first ${h.current.days} race days</span><strong>${statsMoney(h.current.handle)}</strong><small>${h.current.days} racing days · ${h.current.races} races</small></div><div><span>Year-over-year total</span><strong class="${statsTone(h.change)}">${statsPct(h.change)}</strong><div class="handle-dollar-change ${statsTone(h.change)}">${h.current.handle-h.previous.handle>0?'+':''}${statsMoney(h.current.handle-h.previous.handle)}</div><small>2026 minus 2025 · Same number of race days</small></div></div><h3>Average daily handle by weekday</h3><p class="stats-note">Both groups use the same first ${h.current.days} race days. The number of individual weekdays can differ between seasons; each bar shows its day count.</p><div class="handle-legend"><span>● 2025 · first ${h.previous.days} days</span><span>● 2026 · first ${h.current.days} days</span></div>${h.weekdays.map(d=>`<div class="weekday-stat"><div class="weekday-title"><strong>${d.day}</strong><span class="${statsTone(d.averageChange)}">${statsPct(d.averageChange)} avg/day</span></div><div class="handle-bar prior"><span>2025</span><meter min="0" max="${maximum}" value="${d.previous.average||0}" aria-label="${d.day} 2025 average daily handle"></meter><span>${statsMoney(d.previous.average)} <small>(${d.previous.days} days)</small></span></div><div class="handle-bar current"><span>2026</span><meter min="0" max="${maximum}" value="${d.current.average||0}" aria-label="${d.day} 2026 average daily handle"></meter><span>${statsMoney(d.current.average)} <small>(${d.current.days} days)</small></span></div></div>`).join('')}<p class="stats-note">Special and make-up days are included in the YTD totals, but fall outside the Thursday–Sunday comparison. Cancelled and missing-handle cards are excluded. Different meet opening dates and schedules affect total handle.</p><div class="stats-links">${h.documents.map(d=>`<a href="/stats-document?report=${d.key}" target="_blank" rel="noopener noreferrer">${esc(d.label)} ↗</a>`).join('')}</div><p class="stats-note">Source: ${esc(h.source)}${h.updatedAt?' · Dataset saved '+esc(formatted(h.updatedAt)):''}</p>`;
}
function renderStandings(kind){
 const data=statsData[kind],el=document.getElementById(kind+'-body');
 if(data.error){el.innerHTML=freshnessBadge('unavailable')+' '+esc(data.error);return;}
 const query=document.getElementById(kind+'-search').value.trim().toLowerCase();
 const field=document.getElementById(kind+'-sort').value;
 const rows=data.rows.filter(r=>r.name.toLowerCase().includes(query)).slice().sort((a,b)=>(b[field]??-1)-(a[field]??-1)||b.wins-a.wins||a.name.localeCompare(b.name));
 const freshness=data.refreshError?'cached':reportFreshness(data.snapshot?data.savedAt:data.coverageThrough);
 document.getElementById(kind+'-meta').innerHTML=`${freshnessBadge(freshness,data.snapshot&&freshness==='current'?'Latest snapshot':null)}<strong>${esc(data.dateRange)}</strong><span>${data.rows.length} source entries · ${data.snapshot?'Retrieved '+esc(formatted(data.savedAt)):'Saved report'}</span>${data.document?`<a href="${data.document}" target="_blank" rel="noopener noreferrer">${esc(data.documentLabel||'Original PDF')} ↗</a>`:''}<a href="${safeURL(data.sourceURL)}" target="_blank" rel="noopener noreferrer">Equibase source ↗</a>${data.refreshError?`<span class="stale">${esc(data.refreshError)}</span>`:''}`;
 const note=document.getElementById(kind+'-coverage-note');if(note)note.textContent=data.snapshot?'Latest successful scheduled Equibase retrieval. The source does not supply an exact race-day cutoff; retrieval time is shown above. Win % = wins / starts. In the money % = wins, seconds and thirds / starts. Sorted by wins initially.':'Saved report coverage is shown above. Win % = wins / starts. In the money % = wins, seconds and thirds / starts. Sorted by wins initially.';
 const limit=document.getElementById(kind+'-limit').value;
 const display=limit==='all'?rows:rows.slice(0,Number(limit));
 document.getElementById(kind+'-count').textContent=`Showing ${display.length} of ${rows.length} matching source entries`;

 el.innerHTML=display.map((r,i)=>`<article class="standing-row"><div class="standing-name"><span>${String(i+1).padStart(2,'0')}</span><strong>${esc(r.name)}</strong></div><div class="standing-values"><div><span>Starts</span><strong>${r.starts}</strong></div><div><span>Wins</span><strong>${r.wins}</strong></div><div><span>Second</span><strong>${r.second}</strong></div><div><span>Third</span><strong>${r.third}</strong></div><div><span>Win %</span><strong>${r.winPct==null?'—':r.winPct.toFixed(1)+'%'}</strong></div><div><span>In the money %</span><strong>${r.itmPct==null?'—':r.itmPct.toFixed(1)+'%'}</strong></div><div><span>Total earnings</span><strong>${statsMoney(r.earnings)}</strong></div></div></article>`).join('')||'<p class="stats-note">No matching names.</p>';
}
function renderOwners(data){
 const el=document.getElementById('owners-body');
 if(data.error){el.innerHTML=freshnessBadge('unavailable')+' '+esc(data.error);return;}
 const maximum=Math.max(...data.rows.map(r=>r.owners));
 el.innerHTML=`<div class="standings-meta">${freshnessBadge(reportFreshness(data.generated+'T12:00:00-04:00'))}<strong>Saved report · ${esc(statsDate(data.generated))}</strong><a href="${data.document}" target="_blank" rel="noopener noreferrer">Original owners PDF ↗</a></div><p class="stats-note">Distinct owner names in Equibase’s Woodbine standings, including partnerships and stables. ${data.partialYear} is a partial season through ${esc(data.through)}; earlier years are full seasons. These counts use each report’s season coverage.</p><div class="owner-years">${data.rows.map(r=>`<article class="owner-year ${r.year===data.partialYear?'owner-partial':''}"><div class="owner-heading"><h3>${r.year}</h3><strong>${r.owners.toLocaleString('en-CA')} <small>owners</small></strong>${r.year===data.partialYear?`<span class="owner-period">Partial · through ${esc(data.through)}</span>`:'<span class="owner-period">Full season</span>'}</div><meter min="0" max="${maximum}" value="${r.owners}" aria-label="${r.year}: ${r.owners} owners${r.year===data.partialYear?', partial season':''}"></meter><div class="owner-counts">${[['Races run',r.races],['Winners (1+)',r.winners],['2+ wins',r.twoPlus],['5+ wins',r.fivePlus],['10+ wins',r.tenPlus]].map(([label,value])=>`<div><span>${label}</span><strong>${value.toLocaleString('en-CA')}</strong></div>`).join('')}</div></article>`).join('')}</div><p class="stats-note">Source: ${esc(data.source)}. Win tiers count owners with at least that many wins. The partial season is highlighted separately.</p>`;
}
async function loadStats(){try{statsData=await getJSON('/api/woodbine-stats');renderHandle(statsData.handle);renderOwners(statsData.owners);renderStandings('jockey');renderStandings('trainer');document.getElementById('stats-status').textContent='Latest available reports loaded. Jockey and trainer snapshots follow the scheduled Equibase updates.';}catch{document.querySelectorAll('.stats-panel').forEach(markCached);document.getElementById('stats-status').textContent='Could not refresh saved statistics. Retrying automatically.';}}
for(const kind of ['jockey','trainer']){document.getElementById(kind+'-search').addEventListener('input',()=>statsData&&renderStandings(kind));document.getElementById(kind+'-sort').addEventListener('change',()=>statsData&&renderStandings(kind));document.getElementById(kind+'-limit').addEventListener('change',()=>statsData&&renderStandings(kind));}
document.getElementById('stats-refresh').addEventListener('click',loadStats);
loadStats();setInterval(loadStats,60000);
